#looging:
#  level:
#    ROOT: ${ROOT_LOG_LEVEL:ERROR}
#    frolovv.pizza: ${LOG_LEVEL:ERROR}
#    org.hibernate.transaction: ${HIBERNATE_LOG_LEVEL:ERROR}
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: TRACE

spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://${PG_URL:localhost:5432/postgres}
    username: ${PG_USER:postgres}
    password: ${PG_PASSWORD:example}
  application:
# TODO: rename application from pizza to showcase-service
    name: pizza
  jpa:
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      flushMode: MANUAL
      auto_commit: false
      ddl-auto: create-drop
      jdbc:
        batch_size: 30

hibernate.connection.provider_disables_autocommit: true
spring.jpa.properties.org.hibernate.flushMode: MANUAL
spring.jpa.org.hibernate.flushMode: MANUAL
hibernate.show_sql: true

hibernate:
  jdbc:
    batch_size: 30
  order_inserts: true
  order_updates: true